name: Go

on:
  pull_request:
    branches:
      - "*"
  push:
    tags:
      - "**"

jobs:
  go-test:
    strategy:
      fail-fast: false
      matrix:
        go: ["1.25.x"]
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    env:
      CGO_ENABLED: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - if: github.actor == 'nektos/act' && runner.os == 'Linux'
        name: act workaround
        run: apt update && apt install -y zstd gcc git

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
          cache: true
          cache-dependency-path: go.sum

      - name: Show go version
        run: go version

      - name: Run tests
        run: go test -short -cover ./...

  go-lint:
    name: lint
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25.x"
          cache: true
          cache-dependency-path: go.sum

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          args: --timeout=4m

  xgo:
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    needs: [go-test, go-lint]

    strategy:
      fail-fast: false
      matrix:
        go_version: ["1.25.x"]

    runs-on: ubuntu-latest

    env:
      CGO_ENABLED: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: echo "date=$(date +'%F')" >> "$GITHUB_OUTPUT"

      - name: Get current git tag or commit
        id: tag
        run: echo "tag=$(git describe --tags --always)" >> "$GITHUB_OUTPUT"

      - name: Build with xgo
        uses: crazy-max/ghaction-xgo@v2
        with:
          xgo_version: latest
          go_version: ${{ matrix.go_version }}
          pkg: cmd
          dest: build
          prefix: rapinav2-${{ steps.tag.outputs.tag }}
          targets: windows/386,windows/amd64,linux/386,linux/amd64,darwin/386,darwin/amd64
          v: false
          x: false
          race: false
          ldflags: -s -w -X main.build=${{ steps.date.outputs.date }} -X main.version=${{ steps.tag.outputs.tag }}
          buildmode: default

      - name: Run UPX
        uses: crazy-max/ghaction-upx@v2
        with:
          files: |
            ./build/rapinav2-*linux*
            ./build/rapinav2-*windows*
          args: "-9"

      - name: Checksum
        run: |
          cd build
          sha1sum rapinav2* > sha1sum.txt

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.6.2
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/*
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
